name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test --if-present
      - name: Build
        run: pnpm build --if-present
