name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build --if-present
      - name: Deploy
        run: echo "Deploy step placeholder"
